name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up openjdk11
        uses: actions/setup-java@v1
        with:
          java-version: openjdk11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
