name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up openjdk11
        uses: joschi/setup-jdk@v1
        with:
          java-version: 'openjdk11'
          architecture: 'x64' // defaults to 'x64'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
